name: Create and upload release assets

on:
  release:
    types:
      - created

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Determine tag name
        id: tagName
        run: |
          TAG=${GITHUB_REF#refs/*/}
          STRIPPED_TAG=$(echo $TAG | sed -E 's/^v?([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "tag=$STRIPPED_TAG" >> "$GITHUB_OUTPUT"

      - name: Update manifest version
        run: |
          VERSION="${{ steps.tagName.outputs.tag }}.${{ github.run_number }}"
          jq --arg v "$VERSION" '.Version = $v' public/manifest.json > public/manifest.json.tmp
          mv public/manifest.json.tmp public/manifest.json

      - name: NPM Install
        run: npm install
      - name: VUE Build
        run: npm run build
      - name: Streamdeck Bundle
        run: npm run bundle

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/de.perdoctus.streamdeck.homeassistant.streamDeckPlugin
